name: "Bintray Maven Publisher Action"
description: "Upload artifacts to Maven repositories hosted on Bintray"
author: "nagyesta@gmail.com"

inputs:
  DEBUG_LOG:
    description: "Show DEBUG level information on console? (true|false)"
    required: false
    default: "false"
  INFO_LOG:
    description: "Show INFO level information on console? (true|false)"
    required: false
    default: "true"
  WARN_LOG:
    description: "Show WARN level information on console? (true|false)"
    required: false
    default: "true"
  ERROR_LOG:
    description: "Show ERROR level information on console? (true|false)"
    required: false
    default: "true"
  DRY_RUN:
    description: "Allows us to verify values while only simulating uploads."
    required: false
    default: "false"
  POM_FILE_NAME:
    description: "The path where the POM file can be located relative to your content root."
    required: false
  JAR_FILE_NAME:
    description: "The path where the Jar file can be located relative to your content root."
    required: false
  SOURCE_JAR_FILE_NAME:
    description: "The path where the source Jar file can be located relative to your content root."
    required: false
  JAVADOC_JAR_FILE_NAME:
    description: "The path where the Javadoc Jar file can be located relative to your content root."
    required: false
  MANIFEST:
    description: "The path where the Upload manifest file can be located relative to your content root."
    required: false
    default: "manifest.bau"
  ARTIFACT_GROUP_ID:
    description: "The Maven group Id we need to use for this artifact."
    required: false
  ARTIFACT_ARTIFACT_ID:
    description: "The Maven artifact Id we need to use for this artifact."
    required: false
  ARTIFACT_VERSION:
    description: "The Maven optional artifact version we need to use for this artifact. If not specified, the action will attempt to determine the tag name pointing to HEAD."
    required: false
  API_USER:
    description: "The name of your Bintray user we need to use."
    required: true
  API_KEY:
    description: "The token of your Bintray user we need to use."
    required: true
  SUBJECT:
    description: "The name of the subject owning the Bintray repository. Defaults to the API_USER if missing."
    required: false
  REPO:
    description: "The name of the Bintray repository."
    required: true
  PACKAGE_NAME:
    description: "The name of the Bintray package we need to upload to."
    required: true
  BINTRAY_VERSION_PREFIX:
    description: "The prefix used in front of the Maven version in Bintray version names and tag names."
    required: false
    default: "v"
  BASE_URL:
    description: "The API base URL we need to use for the API calls."
    required: false
    default: "https://api.bintray.com/"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "upload"
  color: "blue"
